<?php
/**
 * @file
 * Main module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function views_ef_bootstrap_form_views_exposed_form_alter(array &$form, FormStateInterface &$form_state, $form_id)
{
  if ($display = $form_state->get('display')) {
    /** @var ViewExecutable $view */
    $view = $form_state->get('view');
    $extenders = $view->getDisplay()->getExtenders();
    if (isset($extenders['views_ef_bootstrap']) && !empty($display['display_options']['display_extenders']['views_ef_bootstrap']['views_ef_bootstrap'])) {
      $items = $extenders['views_ef_bootstrap']->getExposeItems();
      $form['#items'] = $items;
      $groups = $extenders['views_ef_bootstrap']->buildTreeData($items);
      $form += $extenders['views_ef_bootstrap']->buildGroups($groups, $form);
    }
  }
}

/**
 *
 */
function views_ef_bootstrap_preprocess_details(&$vars)
{
  if (!empty($vars['element']['#item']['bootstrap'])) {
    $element = [
      '#type' => 'container',
      '#attributes' => ['class' => ['row']],
      '#children' => $vars['children']
    ];
    $vars['children'] = \Drupal::service('renderer')->render($element, FALSE);
  }
}

/**
 *
 */
function views_ef_bootstrap_preprocess_container(&$vars)
{
  if (!empty($vars['element']['#item']['bootstrap'])) {
    $element = [
      '#type' => 'container',
      '#attributes' => ['class' => ['row']],
      '#children' => $vars['children']
    ];
    $vars['children'] = \Drupal::service('renderer')->render($element, FALSE);
  }
}

/**
 * @see hook_form_FORM_ID_alter()
 */
function views_ef_bootstrap_form_alter(&$form, FormStateInterface $formState, $form_id)
{
  if (preg_match("/^views_form_\.*/", $form_id)) {
    if (!empty($form['header']['views_bulk_operations_bulk_form'])) {
      $form['header']['views_bulk_operations_bulk_form']['#type'] = 'details';
      $form['header']['views_bulk_operations_bulk_form']['#title'] = t('Operations');
      if (!empty($form['actions']['submit'])) {
        if ($form['actions']['submit']['#value'] instanceof TranslatableMarkup) {
          $form['actions']['submit']['#value'] = $form['actions']['submit']['#value']->__toString();
        }
        if ($form['actions']['submit']['#value'] === t('Apply to selected items')->__toString()) {
          $form['actions']['submit']['#attributes'] = ['class' => ['visually-hidden']];
        }
      }
    }
  }
}
