<?php
/**
 * @file
 * Main module file.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function views_ef_bootstrap_form_views_exposed_form_alter(array &$form, FormStateInterface &$form_state, $form_id) {
  if ($display = $form_state->get('display')) {
    /** @var ViewExecutable $view */
    $view = $form_state->get('view');
    $extenders = $view->getDisplay()->getExtenders();
    if(isset($extenders['views_ef_bootstrap']) && !empty($display['display_options']['display_extenders']['views_ef_bootstrap']['views_ef_bootstrap'])) {
      $items = $extenders['views_ef_bootstrap']->getExposeItems();
      $form['#items'] = $items;
      $groups = $extenders['views_ef_bootstrap']->buildTreeData($items);
      $form += $extenders['views_ef_bootstrap']->buildGroups($groups, $form);
    }
  }
}
